#!/usr/bin/env python3
"""
Module 5 — HuggingFace Publisher.

Handles pushing the quantized MxMoE model to HuggingFace Hub
with proper tags, model card, and metadata.

Uploads the compressed model checkpoint along with the generated
model card README.md and pipeline metadata.

Usage:
    python -m src.mxmoe.deployment.hf_publisher \\
        --repo_id your-username/sarvam-30b-MxMoE \\
        --model_dir mxmoe/quantized_models

RUN THIS NEXT: After Module 4. Publishes model to HuggingFace Hub.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.core.logger import get_logger
from src.core.auth import resolve_hf_token

logger = get_logger(__name__)

# ── Constants ────────────────────────────────────────────────────────────────
MODEL_ID = "sarvamai/sarvam-30b"
DEFAULT_QUANTIZED_PATH = "mxmoe/quantized_models"


class HFPublisher:
    """Publish the quantized MxMoE model to HuggingFace Hub."""

    def __init__(
        self,
        config=None,
        repo_id: Optional[str] = None,
        model_dir: str = DEFAULT_QUANTIZED_PATH,
        results_dir: str = "mxmoe/outputs",
        output_dir: str = "mxmoe/outputs/module_4_deployment/results",
        tags: Optional[List[str]] = None,
        hf_token: Optional[str] = None,
    ):
        self.repo_id = repo_id
        self.model_dir = Path(model_dir)
        self.results_dir = Path(results_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.tags = tags or [
            "quantized", "moe", "mxmoe", "sarvam",
            "mixed-precision", "compressed-tensors", "vllm",
        ]
        self.hf_token = hf_token

        if config is not None:
            self.hf_token = resolve_hf_token(config)
            self.output_dir = Path(getattr(config.output, "results_dir", str(self.output_dir)))
            self.output_dir.mkdir(parents=True, exist_ok=True)

            deploy_cfg = getattr(config, "deployment", None)
            hf_cfg = getattr(deploy_cfg, "huggingface", None) if deploy_cfg else None

            self.repo_id = getattr(hf_cfg, "repo_id", None) if hf_cfg else None
            if hf_cfg:
                self.tags = list(getattr(hf_cfg, "tags", self.tags))

            out_cfg = getattr(config, "output", None)
            if out_cfg:
                self.model_dir = Path(getattr(out_cfg, "quantized_models_dir", str(self.model_dir)))
                self.results_dir = Path(getattr(out_cfg, "base_dir", str(self.results_dir)))

    def _prepare_upload_dir(self) -> Path:
        """
        Prepare a staging directory with model files + model card.

        Copies the model card README.md into the model directory so it
        gets uploaded alongside the model weights.

        Returns:
            Path to the directory ready for upload.
        """
        # Look for the model card generated by Module 4b
        card_candidates = [
            self.results_dir / "module_4_deployment" / "results" / "README.md",
            self.output_dir / "README.md",
        ]

        for card_path in card_candidates:
            if card_path.exists():
                dest = self.model_dir / "README.md"
                if not dest.exists() or dest.read_text(encoding="utf-8") != card_path.read_text(encoding="utf-8"):
                    shutil.copy2(card_path, dest)
                    logger.info(f"Copied model card: {card_path} → {dest}")
                break
        else:
            logger.warning("No model card README.md found. Upload will proceed without it.")

        return self.model_dir

    def publish(self) -> Dict[str, Any]:
        """
        Push the quantized model to HuggingFace Hub.

        Uses huggingface_hub's upload_folder API to upload the complete
        compressed model directory including weights, config, and model card.

        Returns:
            Dict with repo URL, commit info, and status.
        """
        if not self.repo_id:
            raise ValueError(
                "No repo_id configured. Set deployment.huggingface.repo_id "
                "in configs/mxmoe.yaml or pass --repo_id"
            )

        if not self.model_dir.exists():
            raise FileNotFoundError(
                f"Model directory not found: {self.model_dir}\n"
                "Run Module 2 first to generate the compressed model."
            )

        logger.info("=" * 60)
        logger.info("  MODULE 5: HuggingFace Publication")
        logger.info("=" * 60)

        # ── Resolve token ────────────────────────────────────────────────
        token = self.hf_token
        if not token:
            import os
            token = os.environ.get("HF_TOKEN")
        if not token:
            try:
                from huggingface_hub import HfFolder
                token = HfFolder.get_token()
            except Exception:
                pass
        if not token:
            raise ValueError(
                "No HuggingFace token found. Set HF_TOKEN env var, "
                "run 'huggingface-cli login', or configure model.hf_token "
                "in config.yaml."
            )

        # ── Prepare upload directory ─────────────────────────────────────
        upload_dir = self._prepare_upload_dir()
        logger.info(f"Upload directory: {upload_dir}")

        # Count files
        files = [f for f in upload_dir.rglob("*") if f.is_file()]
        total_size = sum(f.stat().st_size for f in files)
        total_size_gb = total_size / (1024 ** 3)
        logger.info(f"  Files to upload: {len(files)}")
        logger.info(f"  Total size: {total_size_gb:.2f} GB")

        # ── Upload via huggingface_hub ───────────────────────────────────
        try:
            from huggingface_hub import HfApi

            api = HfApi(token=token)

            # Create repo if it doesn't exist
            logger.info(f"Creating/verifying repo: {self.repo_id}")
            api.create_repo(
                repo_id=self.repo_id,
                repo_type="model",
                exist_ok=True,
                private=False,
            )

            # Upload the folder
            logger.info(f"Uploading model to {self.repo_id}...")
            commit_info = api.upload_folder(
                repo_id=self.repo_id,
                folder_path=str(upload_dir),
                repo_type="model",
                commit_message=(
                    "Upload MxMoE mixed-precision quantized model\n\n"
                    "Quantized with MxMoE pipeline: heterogeneous mixed-precision "
                    "quantization for MoE models."
                ),
                ignore_patterns=[
                    "*.pyc",
                    "__pycache__",
                    ".git",
                    "*.log",
                ],
            )

            result = {
                "status": "success",
                "repo_id": self.repo_id,
                "repo_url": f"https://huggingface.co/{self.repo_id}",
                "commit_hash": getattr(commit_info, "oid", str(commit_info)),
                "num_files": len(files),
                "total_size_gb": round(total_size_gb, 2),
            }

            logger.info(f"✓ Published to: https://huggingface.co/{self.repo_id}")

        except ImportError:
            logger.error("huggingface_hub not installed. Install: pip install huggingface-hub")
            result = {
                "status": "failed",
                "error": "huggingface_hub not installed",
            }
        except Exception as exc:
            logger.error(f"Upload failed: {exc}", exc_info=True)
            result = {
                "status": "failed",
                "error": str(exc),
                "repo_id": self.repo_id,
            }

        # ── Save publication report ──────────────────────────────────────
        report_path = self.output_dir / "publication_report.json"
        with open(report_path, "w", encoding="utf-8") as fh:
            json.dump(result, fh, indent=4, ensure_ascii=False, default=str)
        logger.info(f"Publication report saved: {report_path}")

        return result


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Module 4c: HuggingFace Publisher for sarvam-30b MxMoE"
    )
    parser.add_argument(
        "--repo_id", type=str, default=None,
        help="HuggingFace repo ID (e.g., your-username/sarvam-30b-MxMoE)",
    )
    parser.add_argument(
        "--model_dir", type=str, default=DEFAULT_QUANTIZED_PATH,
        help="Path to the compressed model directory",
    )
    parser.add_argument(
        "--results_dir", type=str, default="mxmoe/outputs",
        help="Base results directory containing pipeline outputs",
    )
    parser.add_argument(
        "--output_dir", type=str,
        default="mxmoe/outputs/module_4_deployment/results",
        help="Output directory for publication report",
    )
    parser.add_argument(
        "--hf_token", type=str, default=None,
        help="HuggingFace API token (or set HF_TOKEN env var)",
    )
    args = parser.parse_args()

    publisher = HFPublisher(
        repo_id=args.repo_id,
        model_dir=args.model_dir,
        results_dir=args.results_dir,
        output_dir=args.output_dir,
        hf_token=args.hf_token,
    )

    result = publisher.publish()

    if result["status"] == "success":
        logger.info(f"Publication complete: {result.get('repo_url', '')}")
    else:
        logger.error(f"Publication failed: {result.get('error', 'unknown')}")


if __name__ == "__main__":
    main()
